language: java

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk-ea
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - mvn clean package -Dmaven.javadoc.failOnError=false -Dmaven.javadoc.failOnWarnings=false -DskipTests=true # TODO enable tests once we create a comprehensive test suite
